name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: python -m pip install .[test] --upgrade pip
    - name: Test with pytest
      run: pytest --cov=./ --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      env:
        env_vars: OS,PYTHON
        files: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}